services:
  metadatarr:
    build: .
    container_name: metadatarr
    restart: unless-stopped
    volumes:
      - ./data:/app/store
      - /mnt/external/qBittorrent/Torrents:/torrents
    ports:
      - 9191:9191
